### ISSUE TITLE
Failed on selecting the 5x4.xclbin IPU binary and got system crashed

### ISSUE THREAD

**Issue by ocwins** [amd/RyzenAI-SW#22]
I have tried selecting the 5x4 bin to compile and run the "getting_started_resnet" example in tutorial.

```
set XLNX_VART_FIRMWARE=C:\my real path contains the bins\5x4.xclbin
set XLNX_TARGET_NAME=AMD_AIE2_5x4_Overlay
```

then I did:

`del modelcachekey`
and
`python predict.py`

it outputs:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20231119 11:41:02.857221 13984 vitisai_compile_model.cpp:304] Vitis AI EP Load ONNX Model Success
I20231119 11:41:02.857221 13984 vitisai_compile_model.cpp:305] Graph Input Node Name/Shape (1)
I20231119 11:41:02.858223 13984 vitisai_compile_model.cpp:309]   input : [-1x3x32x32]
I20231119 11:41:02.858223 13984 vitisai_compile_model.cpp:315] Graph Output Node Name/Shape (1)
I20231119 11:41:02.858223 13984 vitisai_compile_model.cpp:319]   output : [-1x10]
I20231119 11:41:02.859220 13984 vitisai_compile_model.cpp:194] use cache key modelcachekey
I20231119 11:41:02.914391 13984 pass_imp.cpp:366] save const info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\const_info_before_const_folding.txt"
I20231119 11:41:03.027454 13984 pass_imp.cpp:275] save fix info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\fix_info.txt"
I20231119 11:41:03.028456 13984 pass_imp.cpp:366] save const info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\const_info_after_const_folding.txt"
I20231119 11:41:03.029455 13984 pass_imp.cpp:393] save const info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\const.bin"
I20231119 11:41:08.036724 13984 compile_pass_manager.cpp:352] Compile mode: aie
I20231119 11:41:08.037638 13984 compile_pass_manager.cpp:353] Debug mode: performance
I20231119 11:41:08.037638 13984 compile_pass_manager.cpp:357] Target architecture: AMD_AIE2_5x4_Overlay
I20231119 11:41:08.038681 13984 compile_pass_manager.cpp:523] Graph name: main_graph, with op num: 439
I20231119 11:41:08.038681 13984 compile_pass_manager.cpp:536] Begin to compile...
W20231119 11:41:11.725446 13984 RedundantOpReductionPass.cpp:663] xir::Op{name = /avgpool/GlobalAveragePool_output_0_DequantizeLinear_Output_vaip_315, type = pool-fix}'s input and output is unchanged, so it will be removed.
I20231119 11:41:11.856766 13984 PartitionPass.cpp:5648] xir::Op{name = output_, type = fix2float} is not supported by current target. Target name: AMD_AIE2_5x4_Overlay, target type: IPU_PHX. Assign it to CPU.
I20231119 11:41:13.074805 13984 compile_pass_manager.cpp:548] Total device subgraph number 3, CPU subgraph number 1
I20231119 11:41:13.074805 13984 compile_pass_manager.cpp:557] Total device subgraph number 3, DPU subgraph number 1
I20231119 11:41:13.074805 13984 compile_pass_manager.cpp:613] Compile done.
I20231119 11:41:13.114380 13984 anchor_point.cpp:428] before optimization:

input_DequantizeLinear_Output <-- identity@ --
input_QuantizeLinear_Output <-- identity@fuse_DPU --
input_QuantizeLinear_Output
after optimization:

input_QuantizeLinear_Output_vaip_426 <-- identity@combine_empty --
input_QuantizeLinear_Output
I20231119 11:41:13.114380 13984 anchor_point.cpp:428] before optimization:

output <-- identity@ --
output_QuantizeLinear_Output <-- identity@fuse_DPU --
output_QuantizeLinear_Output
after optimization:

output_QuantizeLinear_Output_vaip_427 <-- identity@combine_empty --
output_QuantizeLinear_Output
2023-11-19 11:41:13.2172028 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-19 11:41:13.2218850 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
I20231119 11:41:13.278514 13984 custom_op.cpp:133]  Vitis AI EP running 400 Nodes
Image 0: Actual Label cat, Predicted Label truck
```

and stuck here for a while. then it outputs:

```
F20231119 11:41:33.464839  3528 DpuKernelRunner.hpp:734] DPU timeout: (Exception type: class xrt::run::command_error) Command failed to complete successfully (ERT_CMD_STATE_ERROR)
```

executed again:

`python predict.py`

outputs:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20231119 11:43:24.642719  4408 vitisai_compile_model.cpp:304] Vitis AI EP Load ONNX Model Success
I20231119 11:43:24.643863  4408 vitisai_compile_model.cpp:305] Graph Input Node Name/Shape (1)
I20231119 11:43:24.643863  4408 vitisai_compile_model.cpp:309]   input : [-1x3x32x32]
I20231119 11:43:24.643863  4408 vitisai_compile_model.cpp:315] Graph Output Node Name/Shape (1)
I20231119 11:43:24.643863  4408 vitisai_compile_model.cpp:319]   output : [-1x10]
I20231119 11:43:24.644884  4408 vitisai_compile_model.cpp:194] use cache key modelcachekey
2023-11-19 11:43:24.6937628 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-19 11:43:24.6984656 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
I20231119 11:43:24.756196  4408 custom_op.cpp:133]  Vitis AI EP running 400 Nodes
2023-11-19 11:43:24.8166198 [E:onnxruntime:, inference_session.cc:1645 onnxruntime::InferenceSession::Initialize::<lambda_3739cb9c6e53d83c00159a1fc2913f49>::operator ()] Exception during initialization: IOCTL_KIPUDRV_DOWNLOAD_XCLBIN failed: too many links
Traceback (most recent call last):
  File "C:\RyzenAI\SW\tutorial\getting_started_resnet\predict.py", line 34, in <module>
    session = ort.InferenceSession(model.SerializeToString(), providers=providers,
  File "C:\Users\XXX\anaconda3\envs\ryzenai-0.9-20231119-092553\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\XXX\anaconda3\envs\ryzenai-0.9-20231119-092553\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: IOCTL_KIPUDRV_DOWNLOAD_XCLBIN failed: too many links
```

after that,  I set XLNX_VART_FIRMWARE to 1x4 and remove XLNX_TARGET_NAME, I still got the 'too many links' errors.

then I tried to disable the IPU device in device manager, the system froze and won't reboot. (I was using remote desktop, so I don't know if blue screen occurs or not. When I turned the physical screen on, the monitor didn't get any signal from the computer)

**Comment by poganesh** [comment]
The getting started ResNet example works with the `5x4.xclbin`. To ensure a smooth execution using `5x4.xclbin`, make sure to set the following environment variables based on your command-line interface:

**For Command Prompt:**
```batch
set XLNX_VART_FIRMWARE=C:\path\to\5x4.xclbin
set XLNX_TARGET_NAME=AMD_AIE2_5x4_Overlay
```

**For PowerShell:**
```powershell
$env:XLNX_VART_FIRMWARE="C:\path\to\5x4.xclbin"
$env:XLNX_TARGET_NAME="AMD_AIE2_5x4_Overlay"
```
After setting these paths, verify that they have been configured correctly:

**For Command Prompt:**
```batch
SET
```

**For PowerShell:**
```powershell
dir env:
```

This will list all the environment variables and their values.

When switching back to the `1x4.xclbin`, ensure the appropriate binary is selected and clear the `XLNX_TARGET_NAME` variable. Additionally, delete the `modelcachekey` generated while using the `5X4.xclbin`.

**For Command Prompt:**
```batch
set XLNX_VART_FIRMWARE=C:\path\to\1x4.xclbin
set XLNX_TARGET_NAME=""

```

**For PowerShell:**
```powershell
$env:XLNX_VART_FIRMWARE="C:\path\to\1x4.xclbin"
$env:XLNX_TARGET_NAME=""
```

Verify the variable settings using the `SET` command for Command Prompt or `dir env:` for PowerShell.

This approach should help in seamlessly transitioning between 5x4 and 1x4 xclbins.

**Comment by ocwins** [comment]
> The getting started ResNet example works with the `5x4.xclbin`. To ensure a smooth execution using `5x4.xclbin`, make sure to set the following environment variables based on your command-line interface:
> 
> **For Command Prompt:**
> 
> ```batchfile
> set XLNX_VART_FIRMWARE=C:\path\to\5x4.xclbin
> set XLNX_TARGET_NAME=AMD_AIE2_5x4_Overlay
> ```
> 
> **For PowerShell:**
> 
> ```powershell
> $env:XLNX_VART_FIRMWARE="C:\path\to\5x4.xclbin"
> $env:XLNX_TARGET_NAME="AMD_AIE2_5x4_Overlay"
> ```
> 
> After setting these paths, verify that they have been configured correctly:
> 
> **For Command Prompt:**
> 
> ```batchfile
> SET
> ```
> 
> **For PowerShell:**
> 
> ```powershell
> dir env:
> ```
> 
> This will list all the environment variables and their values.
> 
> When switching back to the `1x4.xclbin`, ensure the appropriate binary is selected and clear the `XLNX_TARGET_NAME` variable. Additionally, delete the `modelcachekey` generated while using the `5X4.xclbin`.
> 
> **For Command Prompt:**
> 
> ```batchfile
> set XLNX_VART_FIRMWARE=C:\path\to\1x4.xclbin
> set XLNX_TARGET_NAME
> ```
> 
> **For PowerShell:**
> 
> ```powershell
> $env:XLNX_VART_FIRMWARE="C:\path\to\1x4.xclbin"
> $env:XLNX_TARGET_NAME=""
> ```
> 
> Verify the variable settings using the `SET` command for Command Prompt or `dir env:` for PowerShell.
> 
> This approach should help in seamlessly transitioning between 5x4 and 1x4 xclbins.

As you can see in my top post, I did these things exactly, but it failed and finally made system crashed.

I will try it again, and report the result here.

**Comment by ocwins** [comment]
> The getting started ResNet example works with the `5x4.xclbin`. 

failed again.

set
```
XLNX_TARGET_NAME=AMD_AIE2_5x4_Overlay
XLNX_VART_FIRMWARE=C:\RyzenAI\ryzen-ai-sw-0.9\voe-4.0-win_amd64\5x4.xclbin
```

output
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20231121 09:14:16.718137 18800 vitisai_compile_model.cpp:304] Vitis AI EP Load ONNX Model Success
I20231121 09:14:16.718137 18800 vitisai_compile_model.cpp:305] Graph Input Node Name/Shape (1)
I20231121 09:14:16.718137 18800 vitisai_compile_model.cpp:309]   input : [-1x3x32x32]
I20231121 09:14:16.718137 18800 vitisai_compile_model.cpp:315] Graph Output Node Name/Shape (1)
I20231121 09:14:16.719134 18800 vitisai_compile_model.cpp:319]   output : [-1x10]
I20231121 09:14:16.720134 18800 vitisai_compile_model.cpp:194] use cache key modelcachekey
I20231121 09:14:16.783110 18800 pass_imp.cpp:366] save const info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\const_info_before_const_folding.txt"
I20231121 09:14:16.895910 18800 pass_imp.cpp:275] save fix info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\fix_info.txt"
I20231121 09:14:16.896339 18800 pass_imp.cpp:366] save const info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\const_info_after_const_folding.txt"
I20231121 09:14:16.897387 18800 pass_imp.cpp:393] save const info to "C:\\RyzenAI\\SW\\tutorial\\getting_started_resnet\\modelcachekey\\const.bin"
I20231121 09:14:22.095574 18800 compile_pass_manager.cpp:352] Compile mode: aie
I20231121 09:14:22.096575 18800 compile_pass_manager.cpp:353] Debug mode: performance
I20231121 09:14:22.096575 18800 compile_pass_manager.cpp:357] Target architecture: AMD_AIE2_5x4_Overlay
I20231121 09:14:22.118032 18800 compile_pass_manager.cpp:523] Graph name: main_graph, with op num: 439
I20231121 09:14:22.118032 18800 compile_pass_manager.cpp:536] Begin to compile...
W20231121 09:14:25.818804 18800 RedundantOpReductionPass.cpp:663] xir::Op{name = /avgpool/GlobalAveragePool_output_0_DequantizeLinear_Output_vaip_315, type = pool-fix}'s input and output is unchanged, so it will be removed.
I20231121 09:14:25.959718 18800 PartitionPass.cpp:5648] xir::Op{name = output_, type = fix2float} is not supported by current target. Target name: AMD_AIE2_5x4_Overlay, target type: IPU_PHX. Assign it to CPU.
I20231121 09:14:27.198907 18800 compile_pass_manager.cpp:548] Total device subgraph number 3, CPU subgraph number 1
I20231121 09:14:27.199867 18800 compile_pass_manager.cpp:557] Total device subgraph number 3, DPU subgraph number 1
I20231121 09:14:27.199867 18800 compile_pass_manager.cpp:613] Compile done.
I20231121 09:14:27.240195 18800 anchor_point.cpp:428] before optimization:

input_DequantizeLinear_Output <-- identity@ --
input_QuantizeLinear_Output <-- identity@fuse_DPU --
input_QuantizeLinear_Output
after optimization:

input_QuantizeLinear_Output_vaip_426 <-- identity@combine_empty --
input_QuantizeLinear_Output
I20231121 09:14:27.241194 18800 anchor_point.cpp:428] before optimization:

output <-- identity@ --
output_QuantizeLinear_Output <-- identity@fuse_DPU --
output_QuantizeLinear_Output
after optimization:

output_QuantizeLinear_Output_vaip_427 <-- identity@combine_empty --
output_QuantizeLinear_Output
2023-11-21 09:14:27.3355430 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-21 09:14:27.3403201 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
I20231121 09:14:27.395577 18800 custom_op.cpp:133]  Vitis AI EP running 400 Nodes
Image 0: Actual Label cat, Predicted Label cat
F20231121 09:14:47.580744  6000 DpuKernelRunner.hpp:734] DPU timeout: (Exception type: class xrt::run::command_error) Command failed to complete successfully (ERT_CMD_STATE_ERROR)
```

executed again:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20231121 09:15:00.834801 19848 vitisai_compile_model.cpp:304] Vitis AI EP Load ONNX Model Success
I20231121 09:15:00.834801 19848 vitisai_compile_model.cpp:305] Graph Input Node Name/Shape (1)
I20231121 09:15:00.834801 19848 vitisai_compile_model.cpp:309]   input : [-1x3x32x32]
I20231121 09:15:00.835772 19848 vitisai_compile_model.cpp:315] Graph Output Node Name/Shape (1)
I20231121 09:15:00.835772 19848 vitisai_compile_model.cpp:319]   output : [-1x10]
I20231121 09:15:00.836820 19848 vitisai_compile_model.cpp:194] use cache key modelcachekey
2023-11-21 09:15:00.8864490 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-11-21 09:15:00.8924043 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
I20231121 09:15:00.940857 19848 custom_op.cpp:133]  Vitis AI EP running 400 Nodes
2023-11-21 09:15:00.9988899 [E:onnxruntime:, inference_session.cc:1645 onnxruntime::InferenceSession::Initialize::<lambda_3739cb9c6e53d83c00159a1fc2913f49>::operator ()] Exception during initialization: IOCTL_KIPUDRV_DOWNLOAD_XCLBIN failed: too many links
Traceback (most recent call last):
  File "C:\RyzenAI\SW\tutorial\getting_started_resnet\predict.py", line 34, in <module>
    session = ort.InferenceSession(model.SerializeToString(), providers=providers,
  File "C:\Users\Eli\anaconda3\envs\ryzenai-0.9-20231119-092553\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\Eli\anaconda3\envs\ryzenai-0.9-20231119-092553\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: IOCTL_KIPUDRV_DOWNLOAD_XCLBIN failed: too many links
```

**Comment by ocwins** [comment]
Diver version: 10.106.8.80

**Comment by ocwins** [comment]
You may have seen:
```
Image 0: Actual Label cat, Predicted Label cat
F20231121 09:14:47.580744  6000 DpuKernelRunner.hpp:734] DPU timeout: (Exception type: class xrt::run::command_error) Command failed to complete successfully (ERT_CMD_STATE_ERROR)
```

In the first run, the first image had succeeded, but the following not.

**Comment by ocwins** [comment]
@poganesh 

I have made a test myself, a simple model with dozens of conv2d layers. All conv2d layers in my model are same: 3x3 or 5x5 kernel, 256 channels, and with proper padding (corresponding to kernel size) to keep the image size same between every layers. Input and output have only 1 channel. Image size (input, output and layers) are 32x32 or larger.

That test works while your example doesn't.

**Comment by ocwins** [comment]
@poganesh

7840hs, A SER7 from Beelink. Details are in the attachment file.
[DESKTOP-7840.zip](https://github.com/amd/RyzenAI-SW/files/13515740/DESKTOP-7840.zip)

Microsoft Windows 11 Pro Version 10.0.22631 Build 22631

The conda environment is created by install.bat from ryzen-ai-sw-0.9 which was downloaded from AMD official website.

**Comment by ocwins** [comment]
> Please update your system to the latest release, and kindly let us know if the reported issue persists.

The 4x4 one works well now.

BTW, it seems that the [automatic installation script](https://ryzenai.docs.amd.com/en/latest/inst.html#install-bundled) won't execute 'python installer.py', so the necessary dlls won't be copied into the directory where python is installed on windows.

And there is another question. Shall we periodically  check the page and  manually update the IPU driver, or can we just leave it to 'AMD Software: Adrenalin Edition' (or windows update)?

**Comment by poganesh** [comment]
Yes, the 5x4.xclbin is obsolete now and is replaced by the 4x4.xclbin.
