### ISSUE TITLE
Exception during initialization: CHECK failed: it != end(): key not found: in_scale

### ISSUE THREAD

**Issue by uniartisan** [amd/RyzenAI-SW#61]
I am adapting a large language model for NPU. Since the opt model is only a basic model and cannot complete the dialogue function, I have to adapt other models.

I have followed code:
```
@echo off
python run_onnx.py --model_name %1 --onnx
optimum-cli export onnx -m %1_smoothquant\pytorch --task text-generation-with-past %1_smoothquant\onnx  --framework pt --no-post-process
:: Generate Ortquantized models
python run_onnx.py --model_name %1 --quantize
xcopy %1_smoothquant\onnx\generation_config.json %1_ortquantized
python ..\..\onnx-ops\python\group\matmulint\onnx_group_matmul.py --model %1_ortquantized\model_quantized.onnx --output %1_ortquantized\model_quantized.onnx
```

I adapted my own model for Optimum, Since my model is not supported by smooth_lm. I skipped the first step and started directly from the second step. 

From `example/transformers/models/opt-onnx/run_onnx.py`, I saw: 
```
dqconfig = AutoQuantizationConfig.avx512_vnni(is_static=False, per_channel=False, use_symmetric_activations=True, 
                                                operators_to_quantize=["MatMul"],
                                                )
        print(dqconfig)

        quantizer = ORTQuantizer.from_pretrained("./%s_smoothquant"%args.model_name + "/onnx", file_name="model.onnx")
        model_quantized_path = quantizer.quantize( save_dir="./%s_ortquantized"%args.model_name, quantization_config=dqconfig )        
```

So, I used `AutoQuantizationConfig.avx512_vnni` to quantize my onnx model to int8, and everything is correct until exporting onnx, and this model can be used normally in CPUprovider.

When I use `python ..\..\onnx-ops\python\group\matmulint\onnx_group_matmul.py --model ` to process my own onnx model, it tells me failed( since I see from onnx visualization that there is no MatMulInteger

Finally, I have tried to use AIE provider.
```
if provider is None:
        provider = 'VitisAIExecutionProvider'
        provider_options = {'config_file': str(config_path)}
    else:
        pass
    # Load a model from transformers and export it to ONNX
    model = ORTModelForCausalLM.from_pretrained(model_path, provider=provider, provider_options=provider_options)
    tokenizer = AutoTokenizer.from_pretrained(model_path, padding_side="left")
```

Compile normally after running and get the number of operators running on the CPU and IPU. But in the end I got an error. The complete error log is as follows:

```
2024-03-10 10:55:59.8416034 [W:onnxruntime:Default, vitisai_provider_factory.cc:48 onnxruntime::VitisAIProviderFactory::CreateProvider] Construting a FlexML EP instance in Vitis AI EP
2024-03-10 10:55:59.8486347 [W:onnxruntime:Default, vitisai_execution_provider.cc:117 onnxruntime::VitisAIExecutionProvider::SetFlexMLEPPtr] Assigning the FlexML EP pointer in Vitis AI EP
2024-03-10 10:56:00.4787094 [W:onnxruntime:Default, vitisai_execution_provider.cc:137 onnxruntime::VitisAIExecutionProvider::GetCapability] Trying FlexML EP GetCapability
2024-03-10 10:56:00.4860073 [W:onnxruntime:Default, flexml_execution_provider.cc:180 onnxruntime::FlexMLExecutionProvider::GetCapability] FlexMLExecutionProvider::GetCapability, C:\amd\voe\binary-modules\ResNet.flexml\flexml_bm.signature can't not be found!
2024-03-10 10:56:00.4951032 [W:onnxruntime:Default, vitisai_execution_provider.cc:153 onnxruntime::VitisAIExecutionProvider::GetCapability] FlexML EP ignoring a non-ResNet50 graph
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20240310 10:56:00.503841 132124 vitisai_compile_model.cpp:346] Vitis AI EP Load ONNX Model Success
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:347] Graph Input Node Name/Shape (50)
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:351]          input_ids : [-1x-1]
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:351]          attention_mask : [-1x-1]
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:351]          past_key_values.0.key : [-1x16x-1x128]
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:351]          past_key_values.0.value : [-1x16x-1x128]
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:351]          past_key_values.1.key : [-1x16x-1x128]
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:351]          past_key_values.1.value : [-1x16x-1x128]
I20240310 10:56:00.504835 132124 vitisai_compile_model.cpp:351]          past_key_values.2.key : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.2.value : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.3.key : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.3.value : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.4.key : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.4.value : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.5.key : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.5.value : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.6.key : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.6.value : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.7.key : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.7.value : [-1x16x-1x128]
I20240310 10:56:00.505846 132124 vitisai_compile_model.cpp:351]          past_key_values.8.key : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.8.value : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.9.key : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.9.value : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.10.key : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.10.value : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.11.key : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.11.value : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.12.key : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.12.value : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.13.key : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.13.value : [-1x16x-1x128]
I20240310 10:56:00.506850 132124 vitisai_compile_model.cpp:351]          past_key_values.14.key : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.14.value : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.15.key : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.15.value : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.16.key : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.16.value : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.17.key : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.17.value : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.18.key : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.18.value : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.19.key : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.19.value : [-1x16x-1x128]
I20240310 10:56:00.507855 132124 vitisai_compile_model.cpp:351]          past_key_values.20.key : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:351]          past_key_values.20.value : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:351]          past_key_values.21.key : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:351]          past_key_values.21.value : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:351]          past_key_values.22.key : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:351]          past_key_values.22.value : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:351]          past_key_values.23.key : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:351]          past_key_values.23.value : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:357] Graph Output Node Name/Shape (49)
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:361]          logits : [-1x-1x151936]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:361]          present.0.key : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:361]          present.0.value : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:361]          present.1.key : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:361]          present.1.value : [-1x16x-1x128]
I20240310 10:56:00.508846 132124 vitisai_compile_model.cpp:361]          present.2.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.2.value : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.3.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.3.value : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.4.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.4.value : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.5.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.5.value : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.6.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.6.value : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.7.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.7.value : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.8.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.8.value : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.9.key : [-1x16x-1x128]
I20240310 10:56:00.509847 132124 vitisai_compile_model.cpp:361]          present.9.value : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.10.key : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.10.value : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.11.key : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.11.value : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.12.key : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.12.value : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.13.key : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.13.value : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.14.key : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.14.value : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.15.key : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.15.value : [-1x16x-1x128]
I20240310 10:56:00.510841 132124 vitisai_compile_model.cpp:361]          present.16.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.16.value : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.17.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.17.value : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.18.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.18.value : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.19.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.19.value : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.20.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.20.value : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.21.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.21.value : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.22.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.22.value : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.23.key : [-1x16x-1x128]
I20240310 10:56:00.511835 132124 vitisai_compile_model.cpp:361]          present.23.value : [-1x16x-1x128]
[Vitis AI EP] No. of Operators :   CPU  1986   GEMM   169
[Vitis AI EP] No. of Subgraphs :  GEMM   169
2024-03-10 10:56:01.0325783 [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-03-10 10:56:01.0445078 [W:onnxruntime:, session_state.cc:1171 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
[libprotobuf FATAL C:\Users\xbuild\Desktop\xj3\VAI_RT_WIN_ONNX_EP_ALL\install_dir\include\google/protobuf/map.h:1293] CHECK failed: it != end(): key not found: in_scale
2024-03-10 10:56:01.2654279 [E:onnxruntime:, inference_session.cc:1645 onnxruntime::InferenceSession::Initialize::<lambda_7886affda615b201aacee9192bb1c95a>::operator ()] Exception during initialization: CHECK failed: it != end(): key not found: in_scale
Traceback (most recent call last):
  File "C:\Users\V3\onnxllm\modelutil\model.py", line 116, in <module>
    model, tokenizer = prepare_model(r"C:\\Users\\V3\\onnxllm\\models\\qwen1.5-1.8-Chat-avx512_vnni-quantizer")
  File "C:\Users\V3\onnxllm\modelutil\model.py", line 15, in prepare_model
    model = ORTModelForCausalLM.from_pretrained(model_path, provider=provider, provider_options=provider_options)
  File "C:\Users\V3\.conda\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 662, in from_pretrained
    return super().from_pretrained(
  File "C:\Users\V3\.conda\envs\ryzenai-transformers\lib\site-packages\optimum\modeling_base.py", line 399, in from_pretrained
    return from_pretrained_method(
  File "C:\Users\V3\.conda\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_decoder.py", line 543, in _from_pretrained
    model = ORTModel.load_model(
  File "C:\Users\V3\.conda\envs\ryzenai-transformers\lib\site-packages\optimum\onnxruntime\modeling_ort.py", line 373, in load_model
    return ort.InferenceSession(
  File "C:\Users\V3\.conda\envs\ryzenai-transformers\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\V3\.conda\envs\ryzenai-transformers\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: CHECK failed: it != end(): key not found: in_scale
2024-03-10 10:56:01.3710763 [W:onnxruntime:Default, vitisai_execution_provider.cc:74 onnxruntime::VitisAIExecutionProvider::~VitisAIExecutionProvider] Releasing the FlexML EP pointer in Vitis AI EP
```

Is there any solution to solve this problem? Looking forward to your reply soon.

**Comment by uniartisan** [comment]
[vitisai_ep_report.json](https://github.com/amd/RyzenAI-SW/files/14548713/vitisai_ep_report.json)
[config.json](https://github.com/amd/RyzenAI-SW/files/14548714/config.json)
[context.json](https://github.com/amd/RyzenAI-SW/files/14548715/context.json)
Here are config jsons, which may help a lot

**Comment by sumitn-xilinx** [comment]
Is it possible to share the model too?

**Comment by uday610** [comment]
Hi @uniartisan , 
Yes we will provide flow with INT4 models. With this release you can find INT4 models in PyTorch flow, OPT model inside "opt" folder, and llama2 inside the "llama2" folder. Those use AWQ flow for quantization where the weights are quantized to 4 or 3 bit. We have plan to provide this flow with ONNX as well.

**Comment by sumitn-xilinx** [comment]
Thanks for sharing the model. We will take a look and get back.

**Comment by uniartisan** [comment]
wow, that's fantastic! I have tried opt by pytorch. But my test speed is 50% slower than that in readme, so I have no choice but to use onnx because onnx is faster in CPU operators.( I'm using 8840u w, with 16TOPS NPU)




Looking forward to your new release soon.









李致远

---Original---
From: ***@***.***&gt;
Date: Wed, Mar 13, 2024 02:07 AM
To: ***@***.***&gt;;
Cc: "Zhiyuan ***@***.******@***.***&gt;;
Subject: Re: [amd/RyzenAI-SW] Exception during initialization: CHECK failed: it != end(): key not found: in_scale (Issue #61)




 
Hi @uniartisan ,
 Yes we will provide flow with INT4 models. With this release you can find INT4 models in PyTorch flow, OPT model inside "opt" folder, and llama2 inside the "llama2" folder. Those use AWQ flow for quantization where the weights are quantized to 4 or 3 bit. We have plan to provide this flow with ONNX as well.

**Comment by uniartisan** [comment]
> Hi @uniartisan , With this current release you can find INT4 models in PyTorch flow, OPT model inside "opt" folder, and llama2 inside the "llama2" folder. Those use AWQ flow for quantization where the weights are quantized to 4 or 3 bit. We have plan to provide this flow with ONNX as well.

Hi, @uday610 
Thank you for your reply. That's fantastic! I have tried opt by pytorch. But my test speed is 50% slower than that in readme, so I have no choice but to use onnx because onnx is faster in CPU operators.( I'm using 8840u w, with 16TOPS NPU)

Also, I am confused about which operators AMD has changed in the opt model or the llama model, because I am not a developer familiar with the opt model and the llama model.  Could you please provide me with a workflow that directly imports the awq model from the transformer library for my reference?  Or you can comment the required changes in the source code and readme.  Or do I just need a pre-trained or exported awq model, and then replace the linear operator in the source code?  thank you for your reply.

**Comment by rhenry74** [comment]
i'm getting the same failure from this little script i hacked together
i'm runnning out of RyzenAI-SW\example\transformers\models\opt-onnx
i don't understand the error
any help?

```python
import onnxruntime as ort
#from modeling_ort_amd import ORTFalconForCausalLM
from modeling_ort_amd import ORTModelForCausalLM
from transformers import AutoTokenizer
import pathlib

CURRENT_DIR = pathlib.Path(__file__).parent
path = "opt-1.3b_smoothquant/onnx/"
model_name = "opt-1.3b"
config_file_path = CURRENT_DIR / "vaip_config.json"

provider = "VitisAIExecutionProvider"
provider_options = {'config_file': str(config_file_path)} 

sess_options = ort.SessionOptions()
sess_options.intra_op_num_threads = 0    
sess_options.execution_mode  = ort.ExecutionMode.ORT_PARALLEL     
sess_options.inter_op_num_threads = 0      
sess_options.add_session_config_entry("session.intra_op.allow_spinning", "0")
sess_options.add_session_config_entry("session.inter_op.allow_spinning", "0")

#model = ORTFalconForCausalLM.from_pretrained(path, provider=provider,use_cache=True, use_io_binding=False, session_options=sess_options, provider_options=provider_options)
model = ORTModelForCausalLM.from_pretrained(path, provider=provider,use_cache=True, use_io_binding=False, session_options=sess_options, provider_options=provider_options)
tokenizer = AutoTokenizer.from_pretrained(path +  model_name)

text = "where is the state of virginia?:"
input_ids = tokenizer(text, return_tensors="pt").input_ids
generated_ids = model.generate(
    input_ids,
    max_length=64,
    temperature=0.1,
    num_return_sequences=1,
    early_stopping=True,
)
out = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
print(out)

```

**Comment by rhenry74** [comment]
i got it working by using path = "opt-1.3b_ortquantized/"
