### ISSUE TITLE
issue when run ONNX-e2e google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'

### ISSUE THREAD

**Issue by liqian29** [amd/RyzenAI-SW#94]
when run ONNX-e2e samples, no matter resnet50 or Yolov8

Set environment as guidance and install VAI EP, when run below command:
python user_generate.py --img ..\..\test_resnet.jpg --resize_shape 224 224 4 --mean 51.97 58.39 61.84 --std_dev 41.65 41.65 41.65 --scale 1.0 1.0 1.0

already report protobuf issue as below, please advise how to resolve it

(onnx-vai) C:\Users\GM5.3\RyzenAI-SW\example\onnx-e2e\examples\resnet50\genmodel>python user_generate.py --img ..\..\test_resnet.jpg --resize_shape 224 224 4 --mean 51.97 58.39 61.84 --std_dev 41.65 41.65 41.65 --scale 1.0 1.0 1.0
-- Add Pre Processing to ResNet50 model ...
-- Model Path: ..\models\resnet50_pt.v14.onnx
Traceback (most recent call last):
  File "C:\Users\GM5.3\RyzenAI-SW\example\onnx-e2e\examples\resnet50\genmodel\user_generate.py", line 44, in <module>
    preprocessor = pre.PreProcessor(onnx_model_name, onnx_pre_model_name, input_node_name)
  File "C:\Users\GM5.3\RyzenAI-SW\example\onnx-e2e\examples\resnet50\genmodel\../../..\vitis_customop\preprocess\generic_preprocess.py", line 15, in __init__
    self.base_model = load_model(input_model_path)
  File "C:\Users\GM5.3\RyzenAI-SW\example\onnx-e2e\examples\resnet50\genmodel\../../..\vitis_customop\utils\utils.py", line 53, in load_model
    model = onnx.load(model_path)
  File "C:\Users\GM5.3\anaconda3\envs\onnx-vai\lib\site-packages\onnx\__init__.py", line 210, in load_model
    model = _get_serializer(format, f).deserialize_proto(_load_bytes(f), ModelProto())
  File "C:\Users\GM5.3\anaconda3\envs\onnx-vai\lib\site-packages\onnx\serialization.py", line 118, in deserialize_proto
    decoded = typing.cast(Optional[int], proto.ParseFromString(serialized))
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'

**Comment by liqian29** [comment]
resolved by using git clone Ryzen AI -SW, instead of download and extract.  BTW, only install Vitis AI EP is enough, don't need install ONNXruntime.

**Comment by liqian29** [comment]
Issue closed
